### ISSUE TITLE
rsync after vagrant destroy?

### ISSUE THREAD

**Issue by vinhdizzo** [mitchellh/vagrant-google#129]
Hi,

I know the project directory get's rsync'ed to `/vagrant` in the server that gets spunned up in GCE.  I noticed that the `/vagrant` doesn't get rsync'ed back to the project directory when `vagrant destroy` is executed.  Would it make sense to have this happen?  Thanks.

**Comment by Temikus** [comment]
Hi @vinhdizzo!

I would suggest filing a feature request with vagrant itself to support it in their [rsync implementation](https://www.vagrantup.com/docs/synced-folders/rsync.html).
The current custom syncing mechanism stays with this provider currently only until NFS capability issues are sorted out: https://github.com/mitchellh/vagrant/issues/6781

Cheers,
A.

**Comment by Temikus** [comment]
Deduping on #175 since that issue is more general.

Currently  Vagrant doesn't implement bi-directional sync yet. However, people report that at least 2 plugins achieve that (like `vagrant-unison` or `vagrant-scp`): hashicorp/vagrant#3062

If you have any issues with interoperability - let me know and I'll do my best to see if I can make it work.
