### ISSUE TITLE
`vagrant rsync` command does not work

### ISSUE THREAD

**Issue by bryanwb** [mitchellh/vagrant-google#137]
This is likely related to #85. The [rsync subcommand](https://www.vagrantup.com/docs/cli/rsync.html) does not currently work w/ the google provider. The plugin does not generate the `.vagrant/machines/default/google/synced_folders` file that the `vagrant rsync` command uses to perform the sync.

**Comment by Temikus** [comment]
@bryanwb The change has been reverted due to NFS issues: https://github.com/mitchellh/vagrant-google/issues/94

I was hoping there is an official way to fix this, but considering that upstream bug is not getting update a workaround will probably be needed. Something like a custom action "FixSyncedFolders" which would force disable NFS with each folder.

It's on my list of things to fix when I have some cycles.
Meanwhile - patches are very welcome and I can help with code review.

**Comment by bryanwb** [comment]
@Temikus tks for the quick reply. I have a workaround atm, but I'll try to come back to this

**Comment by numediaweb** [comment]
Any updates on this issue? @Temikus Could you please share your workaround?

**Comment by Temikus** [comment]
@numediaweb Didn't have time to do this yet, I'm afraid. Will be happy to give you pointers or take a look at a PR, if you're willing to do one.

Re:workaround - depends on what you're trying to do. The rsync command is not available but folders do sync via rsync correctly on "up". You need to resync without reprovisioning?

**Comment by Temikus** [comment]
@numediaweb @bryanwb  This should be fixed, new release that uses built-in rsync is now available.
