### ISSUE TITLE
Any way to link an existing GCE instance when doing vagrant up?

### ISSUE THREAD

**Issue by enriquetuya** [mitchellh/vagrant-google#147]
Is there a way to link to a previously created  instance instead when running `vagrant up`? I created an instance, and after deleting that folder I've lost the ability to connect with it with `vagrant ssh`.

**Comment by Temikus** [comment]
Hi @enriquetuya!

No, there's no such functionality since this workflow is not really covered by vagrant.

However, if you've just deleted `.vagrant` folder it should be somewhat easy to restore state by just cross-referencing it with `~/.vagrant.d/` folder, since the local `.vagrant` folder stores just a couple of id's in case of cloud vm's.

Hope it helps!

**Comment by Temikus** [comment]
I'm closing this issue since this looks resolved.
However, if you still have any questions - no worries at all - just reopen and I'll help you right out!
