### ISSUE TITLE
Waiting for SSH to become available...

### ISSUE THREAD

**Issue by mlasala** [mitchellh/vagrant-google#23]
When I run the vagrant up --provider=google I also see all the warnings but when the machine is launched the output get stuck in:
==> default: Waiting for SSH to become available...
After waiting for a long time, nothing change then I press CTRL+C and this is the output:
^C==> default: Waiting for cleanup before exiting...
==> default: Machine is ready for SSH access!
==> default: Terminating the instance...
Vagrant exited after cleanup due to external interrupt.

At this point the VM is terminated and I can't work anymore with my server :(
Any suggestion?

**Comment by IanLewis** [comment]
I have run into this as well. Vagrant will create an instance and if I try to ssh to it using gcloud compute ssh xxxxx right after it's created then I am able to get in. But around the time that the "Waiting for SSH to become available..." messages shows up, I am unable to ssh to the machine anymore.

gcloud compute ssh xxxx also stops working and prints the following error message:

    ssh: connect to host 107.167.178.238 port 22: Connection timed out
    ERROR: (gcloud.compute.ssh) Could not SSH to the instance.  It is possible that your
    SSH key has not propagated to the instance yet. Try running this command again.
    If you still cannot connect, verify that the firewall and instance are set to accept
    ssh traffic.

Looking at the network settings, it seems that the instance should be accepting ssh traffic.

I don't have any problem using ssh with machines that were created manually using the Google cloud SDK.

**Comment by Vad1mo** [comment]
So what is the deal here? Is this an operator error, a bug? Does a workaround exist? @patkar could you write some more details on how to solve this issue? I am new to Vagrant and GCE so at the current state everything is sorcery.

**Comment by Vad1mo** [comment]
Ok guys, I think I got it.  I dived into what @patkar mentioned. 
And I came up with a solution 

**Prerequirement:**
You need to install Google Cloud SDK or setup your local env in a way that allows you to ssh into gce. eg. `ssh you@gce.machine.`

In my case I had already gce key `~/.ssh/google_compute_engine` so for me `ssh -i ~/.ssh/google_compute_engine vad1mo@my.gce.machine` allowed me to login into all gce instances of mine.

When the above is working any you can ssh into gce, all you need to do is to set the user and point to the ssh key on you local machine.

my Vagrant file:
```
    $LOCAL_USER = "vad1mo"  
    $LOCAL_SSH_KEY = "~/.ssh/google_compute_engine"
```

**Comment by alexey** [comment]
@Vad1mo I did the same, from beginning, ssh always success but vagrant not.

**Comment by paulohac** [comment]
I add my pub key into Compute -> Compute Engine -> Metadata -> Tab SSH Keys
but still having the same problem... 
actually i've notice two more keys, probablly added by the gcloud command "$ gcloud auth ssh" 

![screenshot from 2015-01-28 11 27 01](https://cloud.githubusercontent.com/assets/2131066/5936022/d883adba-a6e0-11e4-9cbb-7b825841af31.png)

**Comment by paulohac** [comment]
After $ vagrant up   I'm able to ssh the newly created machine with another terminal session with $ ssh paulo@machine.IP.address.

But with vagrant ssh --debug i get the following error:

DEBUG ssh: Checking key permissions: /home/paulo/.ssh/id_rsa
 INFO ssh: Invoking SSH: ["paulo@23.251.157.61", "-p", "22", "-o", "Compression=yes", "-o", "DSAAuthentication=yes", "-o", "LogLevel=FATAL", "-o", "StrictHostKeyChecking=no", "-o", "UserKnownHostsFile=/dev/null", "-o", "IdentitiesOnly=yes", "-i", "/home/paulo/.ssh/id_rsa"]
Permission denied (publickey).

**Comment by erjohnso** [comment]
Hey folks - looks like we need a better README.  But, I'll document here too:

#### API Authorization
The path to the P12 private key must be set with `google_key_location` and has nothing to do with SSH access. This is what is used to authorize the API requests to Google Compute Engine to create the VM.  It is the private key associated with your Service Account, and you also need to specify your corresponding `google_project_id` and `google_client_email`.

#### SSH Access
If you want to be able to SSH into a GCE VM, you will first need to add your public key to the GCE metadata service for the desired VM user account.  When a VM first boots, a Google-provided daemon is responsible for talking to the internal GCE metadata service and creates local user accounts and their respective `~/.ssh/authorized_keys`.  Most new GCE users will use the Cloud SDK (https://cloud.google.com/sdk/)'s `gcloud compute` to get started with GCE. This utility has built in support for creating SSH key pairs, and uploading the public key to the GCE metadata service.  By default, `glcoud compute` creates a key pair named `~/.ssh/google_compute_engine[.pub]` which is why you see that referenced in the README.

Note that you can use the more standard `~/.ssh/id_rsa[.pub]` files, but you will need to manually add your public key to the GCE metadata service so your VMs will pick up the the key. Note that they public key is typically prefixed with the username, so that the daemon on the VM adds the public key to the correct user account.  See the blow links for more help with SSH and GCE VMs.

* https://cloud.google.com/compute/docs/instances#sshing
* https://cloud.google.com/compute/docs/console#sshkeys

HTH, Eric

**Comment by erjohnso** [comment]
Updated the README, closing this out.

**Comment by vagnerr** [comment]
Additional Advice:
Putty PPK files will not work. Vagrant doesn't like them. You will get the same hang on waiting for ssh. You need a proper rsa key pair.
