### ISSUE TITLE
Unable to provision multiple instances on GCE

### ISSUE THREAD

**Issue by aabdulwahed** [mitchellh/vagrant-google#91]
Hi everyone,
I used the examples you provide in the plugin vagrant examples from this [link](https://github.com/mitchellh/vagrant-google/blob/master/vagrantfile_examples/Vagrantfile.multiple_machines) but virtual machine provisioning stuck in waiting for ssh become available as shown below: 

**Vagrant 1.7.2**

		ubuntu@cis5:/store/wzone/MPI-SACA/google$ vagrant up --provider google
		Bringing machine 'z1c' up with 'google' provider...
		Bringing machine 'z1f' up with 'google' provider...
		==> z1f: Warning! The Google provider doesn't support any of the Vagrant
		==> z1f: high-level network configurations (`config.vm.network`). They
		==> z1f: will be silently ignored.
		==> z1f: Launching an instance with the following settings...
		==> z1f:  -- Name:            nod-1
		==> z1f:  -- Type:            f1-micro
		==> z1f:  -- Disk type:       pd-standard
		==> z1f:  -- Disk size:       10 GB
		==> z1f:  -- Disk name:       
		==> z1f:  -- Image:           debian-7-wheezy-v20150603
		==> z1f:  -- Zone:            us-central1-c
		==> z1f:  -- Network:         default
		==> z1f:  -- Metadata:        '{"zone"=>"US Central 1c"}'
		==> z1f:  -- Tags:            '[]'
		==> z1f:  -- IP Forward:      
		==> z1f:  -- External IP:     
		==> z1f:  -- Autodelete Disk: true
		==> z1c: Warning! The Google provider doesn't support any of the Vagrant
		==> z1c: high-level network configurations (`config.vm.network`). They
		==> z1c: will be silently ignored.
		==> z1c: Launching an instance with the following settings...
		==> z1c:  -- Name:            master
		==> z1c:  -- Type:            f1-micro
		==> z1c:  -- Disk type:       pd-standard
		==> z1c:  -- Disk size:       10 GB
		==> z1c:  -- Disk name:       
		==> z1c:  -- Image:           debian-7-wheezy-v20150603
		==> z1c:  -- Zone:            us-central1-c
		==> z1c:  -- Network:         default
		==> z1c:  -- Metadata:        '{"zone"=>"US Central 1c"}'
		==> z1c:  -- Tags:            '[]'
		==> z1c:  -- IP Forward:      
		==> z1c:  -- External IP:     
		==> z1c:  -- Autodelete Disk: true
		==> z1f: Waiting for instance to become "ready"...
		==> z1c: Waiting for instance to become "ready"...
		==> z1f: Machine is booted and ready for use!
		==> z1f: Waiting for SSH to become available...
		==> z1c: Machine is booted and ready for use!
		==> z1c: Waiting for SSH to become available...

Can you help to solve it ? 

thanks
Ahmed

**Comment by Temikus** [comment]
Hi Ahmed!

From the looks of it, I would say that SSH authorization fails.
For SSH to connect properly, you need to:
1) Populate the fields in the example correctly and make sure the key exists:
```
$LOCAL_USER = "mitchellh"
$LOCAL_SSH_KEY = "~/.ssh/id_rsa"
```
2) Make sure that the key has been uploaded to GCE metadata.
3) Make sure that the key actually matches the specified user.

Relevant README section on GCE metadata:
>Note that you can use the more standard ~/.ssh/id_rsa[.pub] files, but you will need to manually add your public key to the GCE metadata service so your VMs will pick up the the key. Note that they public key is typically prefixed with the username, so that the daemon on the VM adds the public key to the correct user account.
> https://cloud.google.com/compute/docs/instances#sshing
> https://cloud.google.com/compute/docs/console#sshkeys

If you still cannot connect, I'll need the following info to investigate:
1) Plugin version:
```
$ vagrant plugin list
```
2) Debug output of up:
```
vagrant --debug up
```
NOTE: 
- The output will be _very_ large, so make sure you redirect the output e.g. `vagrant --debug up &>vagrant_up.log` and publish it via gist.github.com`
- Debug logs may contain private information, like your Google Project ID, make sure to anonymise it, e.g. change the id to my-google-project-id.

**Comment by aabdulwahed** [comment]
@Temikus , It sounds as you suggest. It is a SSH issue, for debugging, kindly check out my [vagrant_up.log](https://gist.github.com/aabdulwahed/2e93b8f12604c4d2cd90) also I tried to add my public key to meta_data for each instance as shown below, but still unable to ssh instance


         ....... 
         z1f_zone.metadata = {"zone" => "US Central 1c", "ssh" => "MY_PUBLIC_id_rsa.pub_FILE_CONTENT"} 
         ......

**Comment by Temikus** [comment]
@aabdulwahed , yep, keys are not accepted, so the key is either missing from metadata or doesn't match the one on the system/username. The line you quoted is not how this should be done. It should be done on the **GCE Console** itself or through `gcloud` utility, since the keys are added to the instance automatically by GCE.

Here's how to do it through GCE Console:
1) Log into your project console.
2) Compute -> Compute Engine -> Metadata
3) Select SSH Keys in the upper tab.
4) Click "Edit" and add your ssh key (from what I see in your logs `/home/ubuntu/.ssh/id_rsa`) and the corresponding username (from what I see in the logs `ubuntu` in your case).

Here's a helpful screenshot:
![GCE Metadata ssh howto](https://dl.dropboxusercontent.com/u/334637/GCE_Metadata.png)

Let me know if you still have issues.

**Comment by aabdulwahed** [comment]
@Temikus Here is what I did last time 

* First of all, please check out my [Vagrantfile](https://gist.github.com/aabdulwahed/63de3eab27c3f71ecd52) where I set the value of metadata sshKeys as mentioned in [GCE docs](https://cloud.google.com/compute/docs/metadata#default) where they mentioned that sshKeys is list of ssh keys that can be used to connect to instances in the project 

* second, the output of Vagrantfile that provided above is from [here](https://gist.github.com/aabdulwahed/a4c6a95bb996fd7e97a0), It sounds that sshKeys in metadata does not have any effect.

* finally, I uploaded ssh key as you said to google console as show below 
![screenshot from 2015-07-16 18 19 33](https://cloud.githubusercontent.com/assets/5428661/8728906/9114e1a2-2bf0-11e5-97fe-1063c5debd96.png)

still it stuck in ssh step in the following output snippets

		INFO ssh: SSH not up: #<Vagrant::Errors::SSHAuthenticationFailed: SSH authentication failed! This is typically caused by the public/private
		keypair for the SSH user not being properly set on the guest VM. Please
		verify that the guest VM is setup with the proper public key, and that
		the private key path for Vagrant is setup properly as well.>
		 INFO warden: Calling OUT action: #<VagrantPlugins::Google::Action::ReadSSHInfo:0x00000005adab10>
		 INFO connect_google: ...Connected!
		 INFO warden: Calling OUT action: #<VagrantPlugins::Google::Action::ConnectGoogle:0x0000000521d568>
		 INFO warden: Calling OUT action: #<Vagrant::Action::Builtin::ConfigValidate:0x0000000521cfa0>
		DEBUG ssh: Checking key permissions: /home/ubuntu/.ssh/id_rsa
		 INFO ssh: Attempting SSH connection...
		 INFO ssh: Attempting to connect to SSH...
		 INFO ssh:   - Host: 104.197.63.236
		 INFO ssh:   - Port: 22
		 INFO ssh:   - Username: ubuntu
		 INFO ssh:   - Password? false
		 INFO ssh:   - Key Path: ["/home/ubuntu/.ssh/id_rsa"]
		DEBUG ssh: == Net-SSH connection debug-level log START ==
		DEBUG ssh: D, [2015-07-16T18:21:34.492142 #5745] DEBUG -- net.ssh.transport.session[3041c64]: establishing connection to 104.197.63.236:22
		D, [2015-07-16T18:21:34.638582 #5745] DEBUG -- net.ssh.transport.session[3041c64]: connection established
		I, [2015-07-16T18:21:34.639086 #5745]  INFO -- net.ssh.transport.server_version[3040fbc]: negotiating protocol version
		D, [2015-07-16T18:21:34.787470 #5745] DEBUG -- net.ssh.transport.server_version[3040fbc]: remote is `SSH-2.0-OpenSSH_6.0p1 Debian-4+deb7u2'
		D, [2015-07-16T18:21:34.787613 #5745] DEBUG -- net.ssh.transport.server_version[3040fbc]: local is `SSH-2.0-Ruby/Net::SSH_2.9.2 x86_64-linux'
		D, [2015-07-16T18:21:34.934878 #5745] DEBUG -- tcpsocket[30416d8]: read 984 bytes
		D, [2015-07-16T18:21:34.935261 #5745] DEBUG -- tcpsocket[30416d8]: received packet nr 0 type 20 len 980
		I, [2015-07-16T18:21:34.935420 #5745]  INFO -- net.ssh.transport.algorithms[304006c]: got KEXINIT from server
		I, [2015-07-16T18:21:34.935673 #5745]  INFO -- net.ssh.transport.algorithms[304006c]: sending KEXINIT
		D, [2015-07-16T18:21:34.936040 #5745] DEBUG -- tcpsocket[30416d8]: queueing packet nr 0 type 20 len 1684
		D, [2015-07-16T18:21:34.936174 #5745] DEBUG -- tcpsocket[30416d8]: sent 1688 bytes
		I, [2015-07-16T18:21:34.936227 #5745]  INFO -- net.ssh.transport.algorithms[304006c]: negotiating algorithms
		D, [2015-07-16T18:21:34.936463 #5745] DEBUG -- net.ssh.transport.algorithms[304006c]: negotiated:
		* kex: diffie-hellman-group-exchange-sha1
 
Thanks
Ahmed

**Comment by Temikus** [comment]
Hi Ahmed,

Sorry it took long to reply.

I could reproduce the issue with your Vagrantfile. As soon as I removed the `sshKeys` field from the metadata, I could successfully connect to the instances, so that was the culprit.

There's a difference between per-project and per-instance metadata.
If you look at the GCE doc you referenced, you will see the following comment:
`Relative to http://metadata.google.internal/computeMetadata/v1/project/`, so those are instructions on how to set it up per project via API.

However, the metadata settings you've set in your Vagrantfile are 'per-instance', so they need to be set like so:
`{"zone" => "US Central 1c", "sshKeys" => ["temikus:ssh-rsa AAAAVERYLONGSSHPUBLICKEYGOESHERE== temikus@vagrant-dev"]}`
i.e.:
`user:keytype VERYLONGKEY comment`

This, admittedly, can be verified only if you're using the REST response explorer on the sshKeys metadata page.

Thank you for pointing this out, I will submit a documentation bug on this.
Let me know if you have any further issues.

Cheers,
A.

**Comment by aabdulwahed** [comment]
@Temikus , thanks for your help, it works now after adding the username as a key to SSHKEBODY

**Comment by Temikus** [comment]
I would suggest using `vagrant ssh-config` command to achieve what you're trying to do. It generates a ready-to-use SSH config for the machines, so you can access them by hostnames from ssh.

@aabdulwahed 
If you're looking to just get the info, you can parse the output to your liking, like so:
```
λ vagrant ssh-config | grep 'Host \|HostName'
Host z1c
  HostName 104.197.xx.xx
Host z1f
  HostName 104.154.xx.xx
```
More info can be found [here](http://docs.vagrantup.com/v2/cli/ssh_config.html).
Otherwise, you will need to wrap around `vagrant ssh -c` to get more specific info, like subnet, routes, etc.

Since the issue is not in the codebase and documentation bug has been submitted, I'll resolve this issue.

**Comment by erjohnso** [comment]
sgtm - @aabdulwahed, can you close this if you're all set?

**Comment by aabdulwahed** [comment]
@Temikus , thanks for your help ..
